apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-2
  labels:
    app: nginx-2
spec:
  containers:
  - name: nginx
    image: docker.arvancloud.ir/nginx:latest
    imagePullPolicy: IfNotPresent
#    ports:
#    - containerPort: 80
