apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: example-daemonset
  labels:
    app: example-app
spec:
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: example-container
          image: docker.arvancloud.ir/busybox:1.35
          args:
            - /bin/sh
            - -c
            - "while true; do echo Hello from the DaemonSet; sleep 10; done"
          resources:
            limits:
              cpu: "0.1"
              memory: "50Mi"
            requests:
              cpu: "0.05"
              memory: "25Mi"
          ports:
            - containerPort: 8080
